// src/tests/smoke/tenant-health.test.ts

/**
 * Tenant health smoke test.
 *
 * Verifies minimum operational preconditions for a tenant before the
 * intake pipeline can work:
 *   - intakeToken is always set (auto-generated by @default(cuid()))
 *   - At least one PipelineStage with isDefault=true exists
 *   - At least one active AGENT exists
 *   - AssignmentStrategy is configured (or round-robin default is acceptable)
 *
 * The test seeds a minimal "health-check" tenant, runs the assertions,
 * and cleans up after itself.
 *
 * Phase 6a — T57
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { prisma } from "@/lib/prisma";

const TENANT_ID = "t-smoke-health";

async function seedHealthTenant() {
  await prisma.tenant.upsert({
    where: { id: TENANT_ID },
    update: {},
    create: {
      id: TENANT_ID,
      name: "Health Check Tenant",
      slug: TENANT_ID,
      featureFlags: { INTAKE_PIPELINE_V2_ENABLED: true },
    },
  });

  await prisma.department.upsert({
    where: { id: `${TENANT_ID}-dept` },
    update: {},
    create: {
      id: `${TENANT_ID}-dept`,
      tenantId: TENANT_ID,
      name: "Default",
      slug: "default",
    },
  });

  await prisma.pipelineStage.upsert({
    where: { id: `${TENANT_ID}-stage-new` },
    update: {},
    create: {
      id: `${TENANT_ID}-stage-new`,
      tenantId: TENANT_ID,
      name: "New",
      slug: "new",
      position: 0,
      isDefault: true,
    },
  });

  await prisma.assignmentStrategy.upsert({
    where: { tenantId: TENANT_ID },
    update: {},
    create: { tenantId: TENANT_ID, type: "ROUND_ROBIN", config: {} },
  });

  await prisma.user.upsert({
    where: { id: `${TENANT_ID}-agent-1` },
    update: {},
    create: {
      id: `${TENANT_ID}-agent-1`,
      tenantId: TENANT_ID,
      email: `agent1@${TENANT_ID}.test`,
      passwordHash: "x",
      name: "Health Agent",
      role: "AGENT",
      isActive: true,
      departmentId: `${TENANT_ID}-dept`,
    },
  });
}

async function cleanup() {
  await prisma.assignmentStrategy.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.user.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.pipelineStage.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.department.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.tenant.deleteMany({ where: { id: TENANT_ID } });
}

beforeAll(async () => {
  await seedHealthTenant();
});

afterAll(async () => {
  await cleanup();
  await prisma.$disconnect();
});

describe("tenant health checks", () => {
  it("tenant has an intakeToken (auto-generated by @default(cuid()))", async () => {
    const tenant = await prisma.tenant.findUnique({
      where: { id: TENANT_ID },
      select: { intakeToken: true },
    });
    expect(tenant, "Tenant not found").not.toBeNull();
    expect(tenant!.intakeToken).toBeTruthy();
    expect(tenant!.intakeToken.length).toBeGreaterThan(0);
  });

  it("tenant has at least one PipelineStage with isDefault=true", async () => {
    const defaultStage = await prisma.pipelineStage.findFirst({
      where: { tenantId: TENANT_ID, isDefault: true },
    });
    expect(defaultStage, "No default PipelineStage found — dispatch will throw").not.toBeNull();
  });

  it("tenant has at least one active AGENT", async () => {
    const agent = await prisma.user.findFirst({
      where: { tenantId: TENANT_ID, role: "AGENT", isActive: true },
    });
    expect(agent, "No active AGENT found — assignment fallback only").not.toBeNull();
  });

  it("tenant has an AssignmentStrategy configured (ROUND_ROBIN default is acceptable)", async () => {
    const strategy = await prisma.assignmentStrategy.findUnique({
      where: { tenantId: TENANT_ID },
    });
    // AssignmentStrategy is optional — the pipeline falls back to ROUND_ROBIN
    // behaviour if absent.  This test documents the expectation that it IS
    // configured for a healthy production tenant.
    expect(
      strategy,
      "AssignmentStrategy missing — assignment will use fallback (COMPANY_ADMIN target)",
    ).not.toBeNull();
    expect(["ROUND_ROBIN", "LOAD_BALANCED", "SKILL_BASED", "AI_TIERED", "NAMED_POOL"]).toContain(
      strategy!.type,
    );
  });

  it("tenant featureFlags has INTAKE_PIPELINE_V2_ENABLED set to true", async () => {
    const tenant = await prisma.tenant.findUnique({
      where: { id: TENANT_ID },
      select: { featureFlags: true },
    });
    expect(tenant).not.toBeNull();
    const flags = (tenant!.featureFlags ?? {}) as Record<string, unknown>;
    // Explicitly true → pipeline is enabled
    // (absent key is also OK for the pipeline, but health check expects explicit opt-in)
    expect(flags["INTAKE_PIPELINE_V2_ENABLED"]).toBe(true);
  });
});
